version: '3.8'
services:
    clientapp:
        image: travel-mate-client
        build:
            context: .
            dockerfile: pr.Dockerfile
        volumes:
         - '.:/app'
         - '/app/node_modules'
        ports:
         - 3001:3000
        environment:
         - CHOKIDAR_USEPOLLING=true

