name: Docker Image CI

on:
    pull_request:
        branches:
            - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Compute PR ID
      id: compute-pr-id
      run: |
        echo "::set-output name=pr_id::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"
        
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Publish
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: 'travel-mate-client'
        TAG: ${{ steps.compute-pr-id.outputs.pr_id }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:pr-$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:pr-$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:pr-$IMAGE_TAG"

